name: Container Image

on:
  push:
    tags: ["v*.*.*"]

env:
  IMAGE_NAME: tailscale-k8s

jobs:
  build:
    name: Build container image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Get tag
        id: tag
        uses: dawidd6/action-get-tag@v1
      - name: Login to Github Packages
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build & Push
        uses: docker/build-push-action@v2
        with:
          build-args: |
            version=${{ steps.tag.outputs.tag }}
          tags: ghcr.io/vector-im/${{ env.IMAGE_NAME }}:${{ steps.tag.outputs.tag }}
          push: true
